[package]
name = "metamorph"
version = "0.0.0"
authors = ["akindyakov <akindyakov@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2.32"
dirs = "1.0.4"
groestl = "0.8.0"
regex = "1"
tempfile = "3.0"
zbase32 = "0.1"
