[package]
name = "tissue"
version = "0.1.0"
authors = ["akindyakov <akindyakov@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2.32"
groestl = "0.8"
hex = "0.3"
kv = "0.7"
regex = "1"
tempfile = "3.0"
